namespace NodeScope.Domain.Enums;

/// <summary>
/// Kind of persisted output produced by processing an import job.
/// </summary>
public enum GeneratedArtifactType
{
    /// <summary>
    /// Interactive HTML report generated by the Python pipeline.
    /// </summary>
    ReportHtml = 0,

    /// <summary>
    /// Derived CSV describing validation issues or anomalies.
    /// </summary>
    IssuesCsv = 1,

    /// <summary>
    /// Canonical JSON representation of normalized rows.
    /// </summary>
    NormalizedJson = 2,

    /// <summary>
    /// User-filtered tabular export.
    /// </summary>
    FilteredCsv = 3,
}
